import { Component } from '@angular/core';
import { Article } from '../article/article';

@Component({
  selector: 'app-inmemoriam',
  imports: [Article],
  templateUrl: './inmemoriam.html',
  styleUrl: './inmemoriam.css'
})
export class Inmemoriam {
  bender = {
    image: '/thomasbender.jpg',
    title: 'Thomas A. Bender',
    date: 'April 15, 1943 - January 22, 2025',
    content: 'With hearts full of love and gratitude, we celebrate the life of Thomas A. Bender, a devoted husband, father, grandfather, great-grandfather, brother, uncle, and friend. A lifelong resident of East Aurora, New York, Tom passed away on January 22, 2025, at the age of 81. Though he has left this world, his legacy of service, kindness, and dedication to family and community will forever remain.<br><br>Born in Buffalo on April 15, 1943, to Aaron G. and Hazel F. Bender, Tom embodied the values of hard work, generosity, and an adventurous spirit. A 1961 graduate of East Aurora High School, he carried on his family’s entrepreneurial tradition, running a successful multigenerational business. But beyond his career, Tom was a man who lived life with passion and purpose.<br><br>For more than 50 years, he dedicated himself to protecting and serving his community as a firefighter. Honored with a New York State proclamation in 2015 for his service, Tom held many roles, including fire police officer, disaster coordinator, safety officer, and fire chief. He was also an active member and Director of the Firemen’s Memorial Exhibit Center of Western New York, preserving the history and spirit of those who bravely serve.<br><br>Outside of his community service, Tom found joy in the great outdoors and the thrill of competition. He was an avid hunter, golfer, sailor, and bowler. He loved shooting trap skeet, water skiing, ice skating, and working with his hands in plumbing and heating. Whether in action or quiet moments with family, he embraced life fully, always leading with warmth, wisdom, and an unforgettable sense of humor.<br><br>Tom’s greatest love was his family. He shared 61 wonderful years of marriage with his beloved wife, Dianne C. (Merlau) Bender. Together, they built a family filled with love and laughter. He is survived by his devoted son, Randy (Dawn) Bender; his cherished granddaughter, Tommi (Kevin) Fredette; and his adored great-grandson, Alex Fredette. He also leaves behind his brother, William (Marcia) Bender; nieces and nephews Sara (Mike) Phillips, Brandi (Michael) Todd, and Donald (Pamela) Merlau; and great-nephews Cody and Tyler Phillips. He was predeceased by his parents, his son Thomas A. Bender, Jr., and his brother-in-law Donald Merlau.<br><br>Though we mourn his passing, we find comfort in the countless memories he gifted us. His laughter, his wisdom, and his unwavering love will continue to guide and inspire those who knew him. His was a life well lived—full of courage, kindness, and a deep love for family and community.<br><br>A life like Tom’s is not measured by years but by the lives he touched. As we say farewell, we do so with gratitude for having known him and with the certainty that his spirit will live on in the hearts of all who loved him.',
  }

  bayne = {
    image: '/josephbayne.jpeg',
    title: 'Father Joseph Bayne',
    date: 'March 15, 1957 - June 23, 2023',
    content: 'Fr. Joseph William Bayne, Jr., OFM Conv., 66, a Franciscan Friar Conventual of Our Lady of the Angels Province, died on Friday, June 23, 2023, in Chicago.<br><br>He was born on March 15, 1957, in Baltimore, Maryland, a son of the late Joseph William Sr. (1977) and Jean (nee Gorman) Bayne. He is survived by his mother and younger brother, George.<br><br>Fr. Joe, as he was known by so many, was a graduate of Archbishop Curley High School in Baltimore, where he first encountered the Franciscan community, he would join after graduation in 1975. Completing his Novitiate in Ellicott City, Md., he professed Simple Vows on August 15, 1976. He completed his undergraduate degree at St. Hyacinth College and Seminary in Granby, Mass., earning a BA in Philosophy in 1980. After professing Solemn Vows on August 15, 1981, Friar Joseph studied at St. Anthony-on-Hudson in Rensselaer, New York, where he earned his M.Div degree before being ordained to the Priesthood on March 25, 1985.<br><br>From 1985 to 1989, Fr. Joe began his priestly ministry in Shamokin, where he served as Parochial Vicar of St. Stephen Parish and then St. Stanislaus Parish. <br><br>In 1989, Fr. Joe moved to Buffalo, where he began a 29-year ministry at The Franciscan Center, a transitional housing program for runaway and homeless young men from Western New York. The Center served more than 4,000 young men before closing its doors in 2018. For thirteen of his years in Buffalo, Fr. Joe served as Chaplain of Erie County Emergency Services and the Buffalo Fire Department, often known by his call number, ES-11.<br><br>In 2018, Fr. Joseph was reassigned to Chicopee, Massachusetts, where he served briefly as Pastor of St. Stanislaus Bishop and Martyr Parish and Chaplain of the city fire department, before accepting the responsibility of becoming the Associate Director of Formation at the Conventual Franciscans’ Postulancy house in Chicago. This ministry to young men in their first year of formation as friars was very much a reprisal of his years at The Franciscan Center.',
  }

  kavanaugh = {
    image: '/jameskavanaugh.jpg',
    title: 'James J. Kavanaugh',
    date: 'November 17, 1937 - May 8, 2023',
    content: 'Past Chief James J. Kavanaugh passed away on May 8, 2023. He led the NYSAFC as president from 1988-1989.<br><br>Kavanaugh was a longtime member of the Erie County fire service. He was a life member of the East Seneca Fire Company, led the organization as chief from 1971-1974, and served as a commissioner with the West Seneca District #4.  Kavanaugh joined the Vigilant Fire Company in 1991 and was a life member of the organization. He was also a past president of the Erie County Fire Chiefs Mutual Aid Organization and president of the Firemen\'s Memorial Exhibit Center of Western New York.<br><br>A member of NYSAFC since 1968, Kavanaugh was elected to the board of directors in 1980. He had previously served as sergeant-at-arms, as chairman of the former Membership Committee, and as a member of the Annual Conference Committee.<br><br>During his tenure as president, Kavanaugh formed the association\'s Codes Committee and was actively involved in NYSAFC\'s advocacy for residential fire sprinklers. Also, during his term, work began on development of the NYSAFC Fire Chie\'s Reference Guide, which was released in 1989 and is still published today.',
  }

  wutz = {
    image: '/michaelwutz.jpg',
    title: 'Michael P. Wutz',
    date: 'December 14, 1941 - July 26, 2022',
    content: 'FASNY Past President Michael P. Wutz, 80, of Williamsville passed away Tuesday, July 26, 2022. Throughout his exceptional career as a firefighter, Michael was involved in many State and local firefighter organizations.<br><br>He served on the Scholarship and Fire Service Community Achievements Award Committees for FASNY. He served as a Vice President from 2002-2006 and President from 2006-2008. He served the FASNY Foundation as a Director for six years and was the Grants Committee Chairman.<br><br>Michael also was a part of Western New York’s Volunteer Firemen’s Association, serving as its President in 1977. He held various offices with the Erie County Volunteer Firemen’s Association and the Erie County Fire Chiefs Association. In 2018, he was presented with its Lifetime Achievement Award.<br><br>Michael joined Hutchinson Hose Co. in May 1964, serving as an active firefighter for 40 years. During his time at the company, he served as the Financial Secretary, Recording Secretary, Legislative Chairman, Vice President and President. He also served the Williamsville Fire Department as Captain, EMS Squad Captain and Assistant Chief.<br><br>He was appointed to the New York State Fire Advisory Board and served that Board for eight years. He also served on the Erie County Fire Advisory Board for four years. A native to Williamsville, where he was born, raised and lived out his life, Michael attended Williamsville Central, which is now Williamsville South High School. He is survived by his daughter, Kimberly Petcu; his grandson, Nicholas Petcu; and his brother, Thomas Wutz.',
  }
}
